### ISSUE TITLE
Get errors with Korean characters after deployment

### ISSUE THREAD

**Issue by okcleff** [dlarroder/dalelarroder#160]
**Describe the bug**

When I put any Korean characters(ex. `한글`) in the mdx file, I get errors such as below.

In the local environment, it works fine. However, those errors occur after deployment with Vercel.

It even works fine with Japanese and Chinese characters.

Question is... "Is there any limitations depending on languages?"

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/85351198/223606144-6399c3fd-c40c-489b-863c-8647a626eaad.png)

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: ventura 13.0.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dlarroder** [comment]
It should work with other languages similar to your local one, looks like this is a Vercel issue as if it works locally, then it's a cloud issue, closing this for now, feel free to open an issue to Vercel to find out why it doesn't work on their end, thank you!
