### ISSUE TITLE
How do you change put stuff in blog instead of the original ones??

### ISSUE THREAD

**Issue by grilledpython** [dlarroder/dalelarroder#167]
I spent time but couldn't find the directory where the blog posts are saved. Can someone guide me through?

**Comment by dlarroder** [comment]
Hey @grilledpython, I think [this](https://github.com/dlarroder/dalelarroder/discussions/159) thread has the same question as you. Feel free to close this issue when you have it working, thanks!

**Comment by grilledpython** [comment]
Thank you, I found it out!
