### ISSUE TITLE
invalid siteurl in sitemap

### ISSUE THREAD

**Issue by harshascode** [dlarroder/dalelarroder#211]
**Blog URL is wrong in sitemap**
https://www.dalelarroder.com/sitemap.xml

Example: 
https://dalelarroder.com/how-to-share-assets-to-multiple-appslibraries-in-nx

This URL present in Sitemap.

**Comment by dlarroder** [comment]
Hey @harshascode Sorry for the late reply! I have pushed a fix for this in https://github.com/dlarroder/dalelarroder/commit/8ec70edf7280d165ea5f9aaffb8276edcd6f0e01#diff-68c980f6cc36311701d8a04a11d2bd6363c91b7199c333615e4d33b26f2e20e1R7-R9, closing this now as it looks like the [sitemap](https://dalelarroder.com/sitemap.xml) as been fixed, thanks for opening an issue! 💯
