### ISSUE TITLE
Unable to render a project due to the error serializing `.logrocketId` returned from `getStaticProps` in "/"

### ISSUE THREAD

**Issue by w9w** [dlarroder/dalelarroder#43]
Hi, after properly installing everything and upon trying to render a project using yarn or npm, I stumbled upon an error every time:

```
Error: Error serializing `.logrocketId` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

Screenshot:

<img width="1353" alt="Screenshot 2022-06-22 at 20 26 19" src="https://user-images.githubusercontent.com/38838852/175029302-56f5aabb-fa27-406b-a15e-cf7c32b0bf83.png">

Any clues why it could happen and how to fix it?

Best regards,
Max.

**Comment by dlarroder** [comment]
Hello @w9w, you need to create a `.env` file following the `.env.example` in the project root and populate `NEXT_PUBLIC_LOGROCKET_ID=<your_id>`. Hope this helps, thanks!

**Comment by w9w** [comment]
Thank you, Dale, it works now.

Best regards,
Max (@w2w).
